### ISSUE TITLE
Ask a question

### ISSUE THREAD

**Issue by doctorwgd** [crisb-DUT/DnCNN-tensorflow#1]
Dear author, when I using your code, there are an error list as:
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 295, in minimize
    ([str(v) for _, v in grads_and_vars], loss))
ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables ['Tensor("conv1/weights/read:0", shape=(3, 3, 1, 64), dtype=float32)', ......

What should I do.

**Comment by fahaihappy** [comment]
Same error

**Comment by HKCaesar** [comment]
Dear Sir ,in model.py : from guidedfilter import guidedfilter 
ImportError: No module named guidedfilter
what's up?

**Comment by haihuanzxx** [comment]
Same error

**Comment by yliwang** [comment]
the net output self.Y is never used in loss computation, so the error

**Comment by yihongXU** [comment]
hi @yliwang, I ran into the same problem. Is there a solution ?

**Comment by yliwang** [comment]
the output from conv17, self.Y is the generated image, so the loss should be something 
like self.loss = (1.0 / self.batch_size) * tf.nn.l2_loss(self.Y - self.X_), am I right ?

**Comment by doctorwgd** [comment]
Sorry， I havn't resolved the question.




发自网易邮箱大师
On 06/26/2017 19:20, yihongXU wrote:

hi @yliwang, I ran into the same problem. Is there a solution ?

**Comment by crisb-DUT** [comment]
Sorry, I will fix it after my final exam

**Comment by crisb-DUT** [comment]
Thank you all for the issue. I have fixed #issue1, feel free to report other issue.
