### ISSUE TITLE
reuse = true error

### ISSUE THREAD

**Issue by appyfizzA** [crisb-DUT/DnCNN-tensorflow#10]
I tried to run the program for testing (by setting phase = test in main.py) after training and the following error occured:

Variable conv1/weights already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)

This also had happened when I tried to run main.py multiple times consecutively. It seems the weights are created and stored somewhere, and subsequent runs are somehow conflicting with that and hence this error.

**Comment by crisb-DUT** [comment]
What's your environment

**Comment by appyfizzA** [comment]
Anaconda3 Python 3.6.1
tensorflow 1.3.0

Aditi Panda,
Rourkela

**Comment by crisb-DUT** [comment]
Hi @appyfizzA ,

As README describe, the source code is tested on tensorflow1.0.1 and python2.7 with Linux. The API of other version may be different, sorry.

Besides, I provided Dockerfile, with which you could configure environment fastly.

thanks.
