### ISSUE TITLE
--use_gpu=Fasle

### ISSUE THREAD

**Issue by sdlpkxd** [crisb-DUT/DnCNN-tensorflow#12]
Thank you for the project and I enter with some troubles when I run your code using the below commands:

python main.py --phase=test --use_gpu=False

I think it should print "CPU",but it prints "GPU" and "[!] Load failed..." Is there something wrong in the commands above?

**Comment by crisb-DUT** [comment]
This is a bug which is described in #13 . And it haven't been fixed.
