### ISSUE TITLE
--use_gpu=False failed

### ISSUE THREAD

**Issue by sdlpkxd** [crisb-DUT/DnCNN-tensorflow#13]
I try to run your code without GPU using the flowing commands:

python main.py --phase=test --use_gpu=False

But it prints "GPU" and “[!] Load failed...", I think it should print "CPU". Can the type of bool  be used in parser.add_argument()? I don't think so. 
You can refer to  https://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse

**Comment by crisb-DUT** [comment]
Hi @sdlpkxd ,

plz refer to the updated README.

thanks.

**Comment by sdlpkxd** [comment]
When you use argparse to parse boolean command-line arguments, it doesn't work. In you code "parser.add_argument('--use_gpu', dest='use_gpu', type=bool, default=True, help='gpu flag')" in main.py, type=bool maybe Inappropriate. I can not change the work mode to CPU by "python main.py --phase test --use_gpu False"

thank you

**Comment by crisb-DUT** [comment]
Yeah, it is a bug, waiting to be fixed.

**Comment by crisb-DUT** [comment]
Thanks @sdlpkxd to fix it!
