### ISSUE TITLE
Training became slower and slower

### ISSUE THREAD

**Issue by shawleez** [crisb-DUT/DnCNN-tensorflow#19]
I noticed that the training could become slower and slower. The root cause is that in add_noise(), the following line will keep creating truncated_normal tensors each time add_noise() is called:
     noise = sigma / 255.0 * sess.run(tf.truncated_normal(data.shape))

Since add_noise() is called many times in loops, it will create many truncated_normal tensor nodes that make the training become slower and slower.

The better solution shall be creating truncated_normal once outside the training loops, and pass the tensor to add_noise() as an argument. Something like:  
    #outside the training loops 
    norm_tensor = tf.truncated_normal(data.shape)
    ...
    # inside the training loops
    ... = add_noise(image, sigma, sess, norm_tensor)

this problem also exists in evaluate() and test() but their impact is small compared to train()

**Comment by crisb-DUT** [comment]
Thanks @shawleez ,

Your advice is pretty useful, I will try it if I find some gap time. It will be appreciated if you try it and pull a request.

**Comment by crisb-DUT** [comment]
Hi @shawleez ,

Thanks for your advice. @lizhiyuanUSTC has pulled a request (#21) which fixed this problems by putting the operation of adding noise into graph.

Thanks.
