### ISSUE TITLE
For color images

### ISSUE THREAD

**Issue by appyfizzA** [crisb-DUT/DnCNN-tensorflow#24]
It doesn't work for color images.
 @crisb-DUT @lizhiyuanUSTC  could you provide generate_patches.py for color images?

**Comment by crisb-DUT** [comment]
Hi @appyfizzA ,

The current model is trained for gray images. But is quite easy to trained a model for color images. Maybe it's like this:

1. choose your color images training set
2. modify the input and output channel number
3. train your model 

Thanks,
Wenbo

**Comment by appyfizzA** [comment]
Yes, @crisb-DUT but I think it's not enough.

The patch generation process will be different, each patch should be 50 by 50 by 3, isn't it? 
After all, we need to generate patches for color images. That's why I requested for generate_patches.py .

**Comment by crisb-DUT** [comment]
Hi @appyfizzA ,

Sorry for reply so late. You are right that generate_patches.py should be modified. If you are interested in building a model for colored images denoisng, welcome to pull requests.

Thanks,
Wenbo
