### ISSUE TITLE
Bugs found in the source codes

### ISSUE THREAD

**Issue by husqin** [crisb-DUT/DnCNN-tensorflow#6]
1. When I run the main.py using default paramters, I find the PSNR calculated in evaluation stage is weird, namely, it stays at about 3dB after 5 epoches. Then I find a bug in model.py. In the definition block of function `evaluate(self, epoch, counter, test_data)`, the following line may have a bug, that is, `test_data[idx]` (it is read using PIL.Image.open, so the value range is [0, 255]) should not be multiplied by 255. This line
`groundtruth = np.clip(255 * test_data[idx], 0, 255).astype('uint8')`
may be modified to
`groundtruth = np.clip(test_data[idx], 0, 255).astype('uint8')`

2. But PSNR is still too low, about 4dB, which is too low since the noisy image with a sigma=25 already has a PSNR=20dB. Then I find a bug in utils.py. In the definition block of function `cal_psnr(im1, im2)`, the calculation of mse  has a bug, that is, the passed arguments may be a 4-D tensor of size (1, size1, size2, 1), so this line
`mse = (np.abs(im1 - im2) ** 2).sum() / (im1.shape[0] * im1.shape[1])`
may be modified to
`mse = (np.abs(im1 - im2) ** 2).mean())`
then the evaluated PSNR becomes 28dB, which is normal.

**Comment by crisb-DUT** [comment]
Thanks for your report, after testing and verifying I will update the repository.
